name: Build & Upload Bottles

on:
  push:
    branches: [ "main" ]
    paths: [ "Formula/*.rb" ]
  workflow_dispatch:
    inputs:
      formulae:
        description: "Formulae to build (space-separated)"
        required: false
        default: "tusk"

permissions:
  contents: write
  pull-requests: write

jobs:
  bottle_and_publish:
    runs-on: macos-14

    steps:
      - name: Checkout tap
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Build bottle(s)
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            brew test-bot --only-formulae --skip-online-checks \
              --tap="${{ github.repository }}" \
              --testing-formulae "${{ inputs.formulae }}"
          else
            brew test-bot --only-formulae --skip-online-checks \
              --tap="${{ github.repository }}"
          fi

      - name: Upload bottles (commit + push update)
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail

          TAP="${{ github.repository }}"
          TAP_DIR="$(brew --repository "$TAP")"
          echo "PWD=$(pwd)"
          echo "TAP_DIR=$TAP_DIR"

          shopt -s nullglob

          # If bottle files exist in PWD and we're not already in TAP_DIR, copy them across.
          FILES=( *.bottle.json *.bottle.tar.gz )
          if [[ ${#FILES[@]} -gt 0 ]]; then
            if [[ "$(realpath .)" != "$(realpath "$TAP_DIR")" ]]; then
              for f in "${FILES[@]}"; do
                cp -f "$f" "$TAP_DIR"/
              done
            else
              echo "Bottle files are already in the tap directory."
            fi
          else
            echo "No bottles in PWD; assuming test-bot wrote them directly to the tap."
          fi

          echo "Tap now contains:"
          ls -lah "$TAP_DIR"/*.bottle.* || { echo "No bottle files found"; exit 1; }

          # Run pr-upload INSIDE the tap so it edits Formula/tusk.rb and pushes the commit.
          pushd "$TAP_DIR"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          brew pr-upload
          popd