name: Build & Upload Bottles

on:
  push:
    branches: [ "main" ]
    paths: [ "Formula/*.rb" ]
  workflow_dispatch:
    inputs:
      formulae:
        description: "Formulae to build (space-separated)"
        required: false
        default: "tusk"

permissions:
  contents: write
  pull-requests: write

jobs:
  bottle_and_publish:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: Homebrew/actions/setup-homebrew@master

      - name: Build bottle(s)
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            brew test-bot --only-formulae --skip-online-checks \
              --tap="${{ github.repository }}" \
              --testing-formulae "${{ inputs.formulae }}"
          else
            brew test-bot --only-formulae --skip-online-checks \
              --tap="${{ github.repository }}"
          fi

      - name: Upload bottles (commit + push update)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          TAP="${{ github.repository }}"
          TAP_DIR="$(brew --repository "$TAP")"
          shopt -s nullglob
          FILES=( *.bottle.json *.bottle.tar.gz )
          if [[ ${#FILES[@]} -gt 0 && "$(realpath .)" != "$(realpath "$TAP_DIR")" ]]; then
            cp -f "${FILES[@]}" "$TAP_DIR"/
          fi
          ls -lah "$TAP_DIR"/*.bottle.* || { echo "No bottle files found"; exit 1; }
          pushd "$TAP_DIR"
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git"
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          brew pr-upload
          git push origin HEAD:main
          popd