name: Build & Upload Bottles

on:
  push:
    branches: ["**"]
    paths: ["Formula/*.rb"]
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  bottle_and_publish:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: Homebrew/actions/setup-homebrew@master
      - name: Build bottle(s) for tusk
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          brew test-bot --only-formulae --skip-online-checks \
            --tap="${{ github.repository }}" \
            --testing-formulae tusk
      - name: Update formula with bottle and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          TAP="${{ github.repository }}"
          TAP_DIR="$(brew --repository "$TAP")"
          have_files=0
          ls -1 *.bottle*.json *.bottle*.tar.gz >/dev/null 2>&1 && have_files=1 || true
          if [ $have_files -eq 0 ]; then
            ls -1 "$TAP_DIR"/*.bottle*.json "$TAP_DIR"/*.bottle*.tar.gz >/dev/null 2>&1 && have_files=1 || true
          fi
          [ $have_files -eq 1 ] || { echo "No bottle files found"; exit 1; }
          cd "$TAP_DIR"
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git"
          brew pr-upload
          branch="${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}"
          git push origin HEAD:"$branch"