name: Build & Upload Bottles

on:
  push:
    branches: ["**"]
    paths: ["Formula/*.rb"]
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  bottle_and_publish:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: Homebrew/actions/setup-homebrew@master

      - name: Build bottle(s) for tusk
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          brew test-bot --only-formulae --skip-online-checks \
            --tap="${{ github.repository }}" \
            --testing-formulae tusk

      - name: Collect bottles and update formula
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail

          TAP="${{ github.repository }}"
          TAP_DIR="$(brew --repository "$TAP")"

          # Copy any bottle files into the tap checkout (POSIX-safe)
          find . -maxdepth 3 -type f \( -name '*.bottle*.json' -o -name '*.bottle*.tar.gz' \) -print0 \
            | xargs -0 -I{} sh -c 'cp -f "$1" "$2"/' sh {} "$TAP_DIR"

          ls -lah "$TAP_DIR"/*.bottle.* || { echo "No bottle files found"; exit 1; }

          cd "$TAP_DIR"
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git"

          # Insert/refresh bottle block and commit
          brew pr-upload

          # Push back to the same branch that triggered the workflow
          branch="${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}"
          git push origin HEAD:"$branch"