name: Build & Upload Bottles

on:
  push:
    branches: [ "main" ]
    paths: [ "Formula/*.rb" ]
  workflow_dispatch:
    inputs:
      formulae:
        description: "Formulae to build (space-separated)"
        required: false
        default: "tusk"

permissions:
  contents: write
  pull-requests: write

jobs:
  bottle_and_publish:
    runs-on: macos-14
    steps:
      - name: Checkout tap
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Build bottle(s) with test-bot
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            brew test-bot --only-formulae --skip-online-checks \
              --tap="${{ github.repository }}" \
              --testing-formulae "${{ inputs.formulae }}"
          else
            brew test-bot --only-formulae --skip-online-checks \
              --tap="${{ github.repository }}"
          fi

      - name: Show generated bottle files
        run: ls -lah *.bottle.* || true

      - name: Upload bottles to Release & open PR to update formula
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # pr-upload expects *.bottle.json + *.tar.gz in CWD (they are, from test-bot).
          brew pr-upload