name: Build & Upload Bottles

on:
  push:
    branches: [ "main" ]
    paths: [ "Formula/*.rb" ]
  workflow_dispatch:
    inputs:
      formulae:
        description: "Formulae to build (space-separated)"
        required: false
        default: "tusk"

permissions:
  contents: write
  pull-requests: write

jobs:
  bottle_and_publish:
    runs-on: macos-14

    steps:
      - name: Checkout tap
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Build bottle(s)
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            brew test-bot --only-formulae --skip-online-checks \
              --tap="${{ github.repository }}" \
              --testing-formulae "${{ inputs.formulae }}"
          else
            brew test-bot --only-formulae --skip-online-checks \
              --tap="${{ github.repository }}"
          fi

      - name: Upload bottles (commit + push update)
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euxo pipefail

          TAP="${{ github.repository }}"
          TAP_DIR="$(brew --repository "$TAP")"
          echo "Tap dir: $TAP_DIR"

          # Copy generated bottle files into the tap repo root
          shopt -s nullglob
          for f in *.bottle.json *.bottle.tar.gz; do
            cp "$f" "$TAP_DIR"/
          done

          echo "Files now in tap repo:"
          ls -lah "$TAP_DIR"/*.bottle.*

          # Run pr-upload inside the tap repo so it can modify Formula/tusk.rb and push
          pushd "$TAP_DIR"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          brew pr-upload
          popd